from pyspark import pipelines as dp
from pyspark.sql.functions import udf, col, current_timestamp, to_json, struct
from pyspark.sql.types import StringType
from src.common.validation import validate_order


def _validate_order_fields(order_id, customer_id, item_name, quantity, unit_price, order_date):
    return validate_order({
        "order_id": order_id, "customer_id": customer_id, "item_name": item_name,
        "quantity": quantity, "unit_price": unit_price, "order_date": order_date,
    })


validate_udf = udf(_validate_order_fields, StringType())

# Best-effort SQL mirrors of validate_order, for @dp.expect metrics ONLY — NULL
# predicates evaluate as "passing" (CHECK-constraint convention), a cosmetic
# metrics quirk that does NOT affect rejected_orders routing below.
EXPECTATIONS = {
    "valid_required_fields": (
        "order_id IS NOT NULL AND order_id <> '' AND customer_id IS NOT NULL AND customer_id <> '' "
        "AND item_name IS NOT NULL AND item_name <> '' AND quantity IS NOT NULL "
        "AND unit_price IS NOT NULL AND order_date IS NOT NULL"
    ),
    "valid_quantity": "quantity > 0",
    "valid_amount": "quantity * unit_price > 0",
    "valid_order_date": "order_date <= current_timestamp()",
}


@dp.view()
@dp.expect_all(EXPECTATIONS)
def validated_orders():
    bronze = dp.read_stream("bronze_orders")
    return bronze.withColumn(
        "rejection_reason",
        validate_udf(col("order_id"), col("customer_id"), col("item_name"),
                     col("quantity"), col("unit_price"), col("order_date")),
    )


@dp.table(name="rejected_orders", comment="Orders failing validate_order() — routing preserved from V1.")
def rejected_orders():
    v = dp.read_stream("validated_orders")
    bronze_cols = [c for c in v.columns if c != "rejection_reason"]
    return (v.filter(col("rejection_reason").isNotNull())
             .select(col("order_id"), to_json(struct(*bronze_cols)).alias("raw_payload"),
                      col("rejection_reason"), col("_source_file"), col("_ingest_ts"),
                      current_timestamp().alias("rejected_at")))


@dp.table(name="silver_orders_staged")
def silver_orders_staged():
    v = dp.read_stream("validated_orders")
    # order_date arrives as STRING (Auto Loader's inferColumnTypes doesn't auto-detect
    # ISO-8601 date-strings as TIMESTAMP) — validate_order's future-date check already
    # ran on the raw string above (unchanged logic, correct), so it's safe to cast here,
    # after validation, for the rows that actually proceed to AUTO CDC. Gold's watermark
    # requires a genuine TIMESTAMP column; a string that merely looks like one fails
    # with EVENT_TIME_IS_NOT_ON_TIMESTAMP_TYPE.
    return (v.filter(col("rejection_reason").isNull())
             .drop("rejection_reason")
             .withColumn("order_date", col("order_date").cast("timestamp")))


# --- AUTO CDC: replaces the hand-built merge-key MERGE from silver_scd2.py, AND
# replaces compute_record_hash/compute_version_id (V1 only, see hashing.py) — AUTO
# CDC's own column-by-column comparison against the current row is the change
# detection mechanism now, no synthetic hash needed. ---
dp.create_streaming_table(
    name="silver_orders",
    comment="Current + historical order versions (SCD2), AUTO CDC-managed.",
    table_properties={"delta.enableChangeDataFeed": "true"},
)
dp.create_auto_cdc_flow(
    target="silver_orders",
    source="silver_orders_staged",
    keys=["order_id"],
    sequence_by=struct(col("created_time")),
    stored_as_scd_type="2",
    track_history_except_column_list=["created_time"],
)


# No is_current column is auto-generated by AUTO CDC (confirmed) — current-row
# identification is via __END_AT IS NULL.
@dp.view()
def silver_orders_current():
    return dp.read("silver_orders").withColumn("is_current", col("__END_AT").isNull())


WATERMARK = "2 hours"


# Append-only feed of genuinely new-or-changed versions, feeding gold's watermarked
# streaming aggregation. A plain _change_type = 'insert' filter is NOT sufficient on
# its own: a resubmission changing ONLY a track_history_except_column_list-excluded
# column (created_time alone) does not create a new SCD2 version, but DOES emit a
# second 'insert' CDF event sharing the same __START_AT as the real version it's
# updating in place. Deduping on (order_id, __START_AT) within the watermark fixes
# this — a genuine new version always gets a fresh __START_AT.
@dp.table(name="silver_version_events")
def silver_version_events():
    events = (spark.readStream.format("delta").option("readChangeFeed", "true").table("silver_orders")
              .filter("_change_type = 'insert'")
              .withWatermark("order_date", WATERMARK)
              .dropDuplicatesWithinWatermark(["order_id", "__START_AT"]))
    return (events.select("order_id", "customer_id", "item_name", "quantity", "unit_price",
                           "order_date", "created_time")
            .withColumn("event_ts", current_timestamp()))
